# cargo update; cargo upgrade

[package]
name = "op-log"
version = "0.2.5"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.40" }
chrono-tz = "0.10"
flate2 = { version = "1", features = ["zlib-rs"] }
rand = "0.10"
log = "0.4"
[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
